databases:
  - name: vue-js-israel-db
    plan: free
    ipAllowList: []
services:
  - type: web
    env: docker
    name: directus
    plan: free
    healthCheckPath: /server/health
    startCommand: directus bootstrap && directus start
    envVars:
      - key: DB_CLIENT
        value: pg
      - key: DB_HOST
        value: dpg-d0kpok0gjchc73ehvt0g-a
      - key: DB_PORT
        value: 5432
      - key: DB_USER
        value: directus_db_jb9k_user
      - key: DB_DATABASE
        value: directus_db_jb9k
      - key: DB_PASSWORD
        value: MTq9eJh4yw1nclRFxWzKVoBcyqdfqrsZ 
      - key: KEY
        generateValue: true
      - key: SECRET
        generateValue: true
      - key: ADMIN_PASSWORD
        value: admin123
      - key: ADMIN_EMAIL
        value: 'admin@example.com'
      - key: LOG_STYLE
        value: raw
      - key: CORS_ENABLED
        value: true
      - key: CORS_ORIGIN
        value: true
      - key: PORT
        fromService:
          type: web
          name: directus
          property: port
