databases:
  - name: vue-js-israel-db
    plan: free
    ipAllowList: []
services:
  - type: web
    env: docker
    name: directus
    plan: free
    envVars:
      - key: DB_CLIENT
        value: postgres
      - key: DB_CONNECTION_STRING
        fromDatabase:
          name: vue-js-israel-db
          property: connectionString
      - key: KEY
        generateValue: true
      - key: SECRET
        generateValue: true
      - key: ADMIN_PASSWORD
        generateValue: true
      - key: ADMIN_EMAIL
        value: 'barakplasma@gmail.com'
